---  
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "portfolio-deployment"
  namespace: "default"
  labels:
    app: "portfolio-1"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "portfolio-1"
  template:
    metadata:
      labels:
        app: "portfolio-1"
    spec:
      containers:
      - name: "portfolio-sha256-1"
        image: "gcr.io/creativesly/portfolio:v1"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "portfolio-1-hpa-h5om"
  namespace: "default"
  labels:
    app: "portfolio-1"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "portfolio-1"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
